core/urls.py
from django.urls import path, include
from core.panties import index
from . import views

app_name  = "core"

urlpatterns = [
    path("",views.index,name="index"),
    
    path("products/",views.product_list_view,name="product-list"),
    
    path("category/",views.category_list_view,name="category-list"),
    path("category/<cid>",views.product_list_category_view,name="category-product-list"),
    
    path("vendors/",views.vendor_list_view,name="vendor-list"),
    path("vendors/<vid>",views.vendor_detail_view,name="vendor-detail"),
    
    
    path("products/<pid>/",views.product_detail_view,name="product-detail"),
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),
    
    
    path("ajax-add-review/<int:pid>/",views.ajax_add_review,name="ajax-add-review"),
    
    path("search/",views.search_view, name="search"),
    
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    
    path("cart/", views.cart_view, name="cart"),
    
    path("filter-products/", views.filter_product, name="filter-product"),
    
    path("delete-from-cart/", views.delete_item_from_cart,name="delete-from-cart"),
    path("update-cart/", views.update_from_cart,name="update-cart"),
    
    
    path("checkout/<oid>/", views.checkout,name="checkout"),
    
    path("paypal/", include('paypal.standard.ipn.urls')),
    
    path("payment-completed/<oid>", views.payment_completed_view,name="payment-completed"),
    # path("payment-completed/", views.payment_completed_view,name="payment-completed"),
    
    path("payment-failed/", views.payment_failed_view,name="payment-failed"),
    
    
    path("dashboard/", views.customer_dashboard,name="dashboard"),
    
    path("dashboard/order/<int:id>", views.order_detail,name="order-detail"),
    
    path("make-default-address", views.make_address_default,name="make-default-address"),
    
    path("wishlist/", views.wishlist_view,name="wishlist"),
    path("add-to-wishlist/",views.add_to_wishlist,name="add-to-wishlist"),
    path("remove-from-wishlist/",views.remove_wishlist,name="remove-from-wishlist"),

    
    path("contact/",views.contact,name="contact"),
    path("ajax-contact-form/",views.ajax_contact_form,name="ajax_contact"),
    
    
    
    path("save_checkout_info/",views.save_checkout_info, name="save-checkout-info"),
    
    path("api/create_checkout_session/<oid>/", views.create_checkout_session,name="create_checkout_session")

    
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("useradmin/",include("useradmin.urls")),

]
if settings.DEBUG:
    
 urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

useradmin/urls.py
from django.urls import path
from useradmin import views

app_name  = "useradmin"

urlpatterns = [
    path("dashboard/",views.dashboard, name="dashboard"),
    path("products/",views.products, name="products"),
    path("add_product/",views.add_product, name="add_product"),
    path("edit_product/<pid>",views.edit_product, name="edit_product"),
    path("delete_product/<pid>",views.delete_product, name="delete_product"),
    path("orders",views.orders, name="orders"),
    path("orders_detail/<id>/",views.order_detail, name="order_detail"),
    path("change_order_status/<oid>/",views.change_order_status, name="change_order_status"),
    path("shop_page/",views.shop_page, name="shop_page"),
    path("reviews/",views.reviews, name="reviews"),
]

useradmin/models.py
from django.db import models

# Create your models here.

useradmin/forms.py
from core.models import Product
from django import forms

class AddProductForm(forms.ModelForm):
    
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title", "class":"form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Product Description", "class":"form-control"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={"placeholder": "Sale Price", "class":"form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(attrs={"placeholder": "Old Price", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Type of product e.g organic cream", "class":"form-control"}))
    stock_count = forms.CharField(widget=forms.NumberInput(attrs={"placeholder": "How many are in stock?", "class":"form-control"}))
    life = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "How long would this product live?", "class":"form-control"}))
    # mfd = forms.DateTimeField(widget=forms.DateTimeInput(attrs={"placeholder": "e.g. 22-11-02", "class":"form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Tags", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))

    
    class Meta:
        
        model = Product
        fields = [
            "title",
            "image",
            "description",
            "price",
            "old_price",
            "specifications",
            "type",
            "stock_count",
            "life",
            "mfd",
            "tags",
            "digital",
            "category",
        ]

useradmin/views.py
from django.shortcuts import render, redirect
from core.models import CartOrder , Product, Category  , CartOrderItems,ProductReview
from django.db.models import Sum
from userauths.models import User
from django.db.models.functions import ExtractMonth
from django.views.decorators.csrf import csrf_exempt
import datetime
from useradmin.forms import AddProductForm
from django.contrib import messages

def dashboard(request):
    revenue = CartOrder.objects.aggregate(price = Sum("price"))
    total_orders_count = CartOrder.objects.all()
    all_products = Product.objects.all()
    all_categories = Category.objects.all()
    new_customers = User.objects.all().order_by("-id")
    latest_orders = CartOrder.objects.all()
    this_month = datetime.datetime.now().month
    monthly_revenue = CartOrder.objects.annotate(
    order_date_month=ExtractMonth('order_date')
).filter(order_date_month=this_month).aggregate(price=Sum('price'))
    
    context = {
        
        "revenue":revenue,
        "total_orders_count":total_orders_count,
        "all_products":all_products,
        "all_categories":all_categories,
        "new_customers":new_customers,
        "latest_orders":latest_orders,
        "monthly_revenue":monthly_revenue,
        
    }
    return render(request, "useradmin/dashboard.html",context)
    
    
def products(request):
    all_products = Product.objects.all().order_by("-id")
    all_categories = Category.objects.all()
    
    context = {
        
        "all_products":all_products,
        "all_categories":all_categories,   
    }
    return render(request, "useradmin/products.html",context)
    

    
def add_product(request):
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            form.save_m2m()
            return redirect("useradmin:dashboard")
    else:
        form = AddProductForm()
        
    context = {
        "form":form
        
    }   
    return render(request,"useradmin/add-product.html"
                  ,context)
    
def edit_product(request, pid):
    product = Product.objects.get(pid=pid)
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES,instance=product)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            form.save_m2m()
            return redirect("useradmin:edit_product",product.pid)
    else:
        form = AddProductForm(instance=product)
        
    context = {
        "form":form,
        "product":product,
        
    }   
    return render(request,"useradmin/edit-product.html",context)



def delete_product(request, pid):
    product = Product.objects.get(pid=pid)
    product.delete()
    return redirect("useradmin:products")

def orders(request):
    orders = CartOrder.objects.all()
    context = {
        "orders":orders,
    }
    return render(request,"useradmin/orders.html",context)


def order_detail(request,id):
    order = CartOrder.objects.get(id=id) 
    order_items = CartOrderItems.objects.filter(order = order)
    context = {
        "order":order,
        "order_items":order_items,
        
    }
    return render(request,"useradmin/order_detail.html",context)


@csrf_exempt
def change_order_status(request,oid):
    order = CartOrder.objects.get(oid= oid)
    if request.method == 'POST':
        status = request.POST.get("status")
        print("status =====",status)
        order.product_status = status
        order.save()
        messages.success(request,f"Order status changed to {status}")
        
    return redirect('useradmin:order_detail',order.id)


def shop_page(request):
    products = Product.objects.all()
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    total_sales = CartOrderItems.objects.filter(order__paid_status = True).aggregate(qty=Sum("qty"))
    
    context = {
        "products":products,
        "revenue":revenue,
        "total_sales":total_sales,
        
    }
    return render(request,"useradmin/shop_page.html",context)
    
    
def reviews(request):
    reviews = ProductReview.objects.all()
    
    context = {
        "reviews":reviews
    }
    return render(request,"useradmin/reviews.html",context)
        
        
        
        
     

templates/useradmin/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Nest Dashboard</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="admin/imgs/theme/favicon.svg" />
        <!-- Template CSS -->
        <script src="{% static 'admin/js/vendors/color-modes.js' %}"></script>
        <link rel="stylesheet"  href="{% static 'admin/css/main.css' %}"/>
    </head>

    <body>
        <div class="screen-overlay"></div>
        <aside class="navbar-aside" id="offcanvas_aside">
            <div class="aside-top">
                <a href="index.html" class="brand-wrap">
                    <img src="{% static 'admin/imgs/theme/logo.svg' %}" class="logo" alt="Nest Dashboard" />
                </a>
                <div>
                    <button class="btn btn-icon btn-aside-minimize"><i class="text-muted material-icons md-menu_open"></i></button>
                </div>
            </div>
            <nav>
                <ul class="menu-aside">
                    <li class="menu-item active">
                        <a class="menu-link" href="/useradmin/">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="">
                            <i class="icon material-icons md-shopping_bag"></i>
                            <span class="text">Products</span>
                        </a>
                        <div class="submenu">
                            <a href="{% url 'useradmin:products' %}">Product List</a>
                            {% comment %} <a href="page-products-grid.html">Product grid</a>
                            <a href="page-products-grid-2.html">Product grid 2</a>
                            <a href="page-categories.html">Categories</a> {% endcomment %}
                        </div>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="page-orders-1.html">
                            <i class="icon material-icons md-shopping_cart"></i>
                            <span class="text">Orders</span>
                        </a>
                        <div class="submenu">
                            <a href="{% url 'useradmin:orders' %}">Order list</a>
                           
                        </div>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="{% url 'useradmin:shop_page' %}">
                            <i class="icon material-icons md-store"></i>
                            <span class="text">Shop Page</span>
                        </a>
                        <div class="submenu">
                            <a href="{% url 'useradmin:shop_page' %}">Shop Page</a>
                        </div>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="page-form-product-1.html">
                            <i class="icon material-icons md-add_box"></i>
                            <span class="text">Reviews</span>
                        </a>
                        <div class="submenu">
                            <a href="{% url 'useradmin:reviews' %}">reviews</a>
                        
                        </div>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="page-transactions-1.html">
                            <i class="icon material-icons md-monetization_on"></i>
                            <span class="text">Transactions</span>
                        </a>
                        <div class="submenu">
                            <a href="page-transactions-1.html">Transaction 1</a>
                            <a href="page-transactions-2.html">Transaction 2</a>
                        </div>
                    </li>
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="#">
                            <i class="icon material-icons md-person"></i>
                            <span class="text">Account</span>
                        </a>
                        <div class="submenu">
                            <a href="page-account-login.html">User login</a>
                            <a href="page-account-register.html">User registration</a>
                            <a href="page-error-404.html">Error 404</a>
                        </div>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="page-reviews.html">
                            <i class="icon material-icons md-comment"></i>
                            <span class="text">Reviews</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="page-brands.html"> <i class="icon material-icons md-stars"></i> <span class="text">Brands</span> </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" disabled href="#">
                            <i class="icon material-icons md-pie_chart"></i>
                            <span class="text">Statistics</span>
                        </a>
                    </li>
                </ul>
                <hr />
                <ul class="menu-aside">
                    <li class="menu-item has-submenu">
                        <a class="menu-link" href="#">
                            <i class="icon material-icons md-settings"></i>
                            <span class="text">Settings</span>
                        </a>
                        <div class="submenu">
                            <a href="page-settings-1.html">Setting sample 1</a>
                            <a href="page-settings-2.html">Setting sample 2</a>
                        </div>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="page-blank.html">
                            <i class="icon material-icons md-local_offer"></i>
                            <span class="text"> Starter page </span>
                        </a>
                    </li>
                </ul>
                <br />
                <br />
            </nav>
        </aside>
        {% block content %}

    
    {% endblock content %}
        
        <script src="{% static 'admin/js/vendors/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'admin/js/vendors/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'admin/js/vendors/select2.min.js' %}"></script>
        <script src="{% static 'admin/js/vendors/perfect-scrollbar.js' %}"></script>
        <script src="{% static 'admin/js/vendors/jquery.fullscreen.min.js' %}"></script>
        <script src="{% static 'admin/js/vendors/chart.js' %}"></script>
        <!-- Main Script -->
        <script src="{% static 'admin/js/main.js' %}" type="text/javascript"></script>
        <script src="{% static 'admin/js/custom-chart.js' %}" type="text/javascript"></script>
    </body>
</html>

templates/useradmin/products.html
{% extends "useradmin/base.html" %}
{% load static %}
{% block content %}
<main class="main-wrap">
    <header class="main-header navbar">
        <div class="col-search">
            <form class="searchform">
                <div class="input-group">
                    <input list="search_terms" type="text" class="form-control" placeholder="Search term" />
                    <button class="btn btn-light bg" type="button"><i class="material-icons md-search"></i></button>
                </div>
                <datalist id="search_terms">
                    <option value="Products"></option>
                    <option value="New orders"></option>
                    <option value="Apple iphone"></option>
                    <option value="Ahmed Hassan"></option>
                </datalist>
            </form>
        </div>
        <div class="col-nav">
            <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link btn-icon" href="#">
                        <i class="material-icons md-notifications animation-shake"></i>
                        <span class="badge rounded-pill">3</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                </li>
                <li class="dropdown nav-item">
                    <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownLanguage" aria-expanded="false"><i class="material-icons md-public"></i></a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownLanguage">
                        <a class="dropdown-item text-brand" href="#"><img src="assets/imgs/theme/flag-us.png" alt="English" />English</a>
                        <a class="dropdown-item" href="#"><img src="assets/imgs/theme/flag-fr.png" alt="Français" />Français</a>
                        <a class="dropdown-item" href="#"><img src="assets/imgs/theme/flag-jp.png" alt="Français" />日本語</a>
                        <a class="dropdown-item" href="#"><img src="assets/imgs/theme/flag-cn.png" alt="Français" />中国人</a>
                    </div>
                </li>
                <li class="dropdown nav-item">
                    <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="assets/imgs/people/avatar-2.png" alt="User" /></a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                        <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                        <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                        <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                        <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                        <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-danger" href="#"><i class="material-icons md-exit_to_app"></i>Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </header>


    <section class="content-main">
        <div class="content-header">
            <div>
                <h2 class="content-title card-title">Products List</h2>
                <p>Lorem ipsum dolor sit amet.</p>
            </div>
            <div>
                <a href="#" class="btn btn-light rounded font-md">Export</a>
                <a href="#" class="btn btn-light rounded font-md">Import</a>
                <a href="{% url 'useradmin:add_product' %}" class="btn btn-primary btn-sm rounded">Create new</a>
            </div>
        </div>


        <div class="card mb-4">
            <header class="card-header">
                <div class="row align-items-center">
                    <div class="col col-check flex-grow-0">
                        <div class="form-check ms-2">
                            <input class="form-check-input" type="checkbox" value="" />
                        </div>
                    </div>
                    <div class="col-md-3 col-12 me-auto mb-md-0 mb-3">
                        <select class="form-select">
                            <option selected>All category</option>
                            <option>Electronics</option>
                            <option>Clothes</option>
                            <option>Automobile</option>
                        </select>
                    </div>
                    <div class="col-md-2 col-6">
                        <input type="date" value="02.05.2021" class="form-control" />
                    </div>
                    <div class="col-md-2 col-6">
                        <select class="form-select">
                            <option selected>Status</option>
                            <option>Active</option>
                            <option>Disabled</option>
                            <option>Show all</option>
                        </select>
                    </div>
                </div>
            </header>
            <!-- card-header end// -->
            <div class="card-body">
                {% for p in all_products %}
                <article class="itemlist">
                    <div class="row align-items-center">
                        <div class="col col-check flex-grow-0">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" />
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                            <a class="itemside" href="#">
                                <div class="left">
                                    <img src="{{p.image.url}}" class="img-sm img-thumbnail" alt="Item" />
                                </div>
                                <div class="info">
                                    <h6 class="mb-0">{{p.title}}</h6>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{p.price}}</span></div>
                        <div class="col-lg-2 col-sm-2 col-4 col-status">
                            <span class="badge rounded-pill alert-success">{{p.status}}</span>
                        </div>
                        <div class="col-lg-1 col-sm-2 col-4 col-date">
                            <span>{{p.date|date:"d M, Y"}}</span>
                        </div>
                        <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                            <a href="{% url 'useradmin:edit_product' p.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                            <a href="{% url 'useradmin:delete_product' p.pid %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                        </div>
                    </div>
                    <!-- row .// -->
                </article>
                {% endfor %}

            </div>
            <!-- card-body end// -->
        </div>










        <!-- card end// -->
        <div class="pagination-area mt-30 mb-50">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-start">
                    <li class="page-item active"><a class="page-link" href="#">01</a></li>
                    <li class="page-item"><a class="page-link" href="#">02</a></li>
                    <li class="page-item"><a class="page-link" href="#">03</a></li>
                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                    <li class="page-item"><a class="page-link" href="#">16</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>


    <!-- content-main end// -->
    <footer class="main-footer font-xs">
        <div class="row pb-30 pt-15">
            <div class="col-sm-6">
                <script>
                    document.write(new Date().getFullYear());
                </script>
                &copy; Nest - HTML Ecommerce Template .
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end">All rights reserved</div>
            </div>
        </div>
    </footer>
</main>

{% endblock content %}