core/urls.py
from django.urls import path, include
from core.panties import index
from . import views

app_name  = "core"

urlpatterns = [
    path("",views.index,name="index"),
    
    path("products/",views.product_list_view,name="product-list"),
    
    path("category/",views.category_list_view,name="category-list"),
    path("category/<cid>",views.product_list_category_view,name="category-product-list"),
    
    path("vendors/",views.vendor_list_view,name="vendor-list"),
    path("vendors/<vid>",views.vendor_detail_view,name="vendor-detail"),
    
    
    path("products/<pid>/",views.product_detail_view,name="product-detail"),
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),
    
    
    path("ajax-add-review/<int:pid>/",views.ajax_add_review,name="ajax-add-review"),
    
    path("search/",views.search_view, name="search"),
    
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    
    path("cart/", views.cart_view, name="cart"),
    
    path("filter-products/", views.filter_product, name="filter-product"),
    
    path("delete-from-cart/", views.delete_item_from_cart,name="delete-from-cart"),
    path("update-cart/", views.update_from_cart,name="update-cart"),
    
    
    path("checkout/<oid>/", views.checkout,name="checkout"),
    
    path("paypal/", include('paypal.standard.ipn.urls')),
    
    path("payment-completed/<oid>", views.payment_completed_view,name="payment-completed"),
    # path("payment-completed/", views.payment_completed_view,name="payment-completed"),
    
    path("payment-failed/", views.payment_failed_view,name="payment-failed"),
    
    
    path("dashboard/", views.customer_dashboard,name="dashboard"),
    
    path("dashboard/order/<int:id>", views.order_detail,name="order-detail"),
    
    path("make-default-address", views.make_address_default,name="make-default-address"),
    
    path("wishlist/", views.wishlist_view,name="wishlist"),
    path("add-to-wishlist/",views.add_to_wishlist,name="add-to-wishlist"),
    path("remove-from-wishlist/",views.remove_wishlist,name="remove-from-wishlist"),

    
    path("contact/",views.contact,name="contact"),
    path("ajax-contact-form/",views.ajax_contact_form,name="ajax_contact"),
    
    
    
    path("save_checkout_info/",views.save_checkout_info, name="save-checkout-info"),
    
    path("api/create_checkout_session/<oid>/", views.create_checkout_session,name="create_checkout_session")

    
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("useradmin/",include("useradmin.urls")),

]
if settings.DEBUG:
    
 urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_list_or_404
from core.models import Product, Category, Vendor, CartOrder, CartOrderItems, ProductImages, ProductReview, Wishlist, Address, Coupon

from taggit.models import Tag
from django.template.loader import render_to_string
from core.form import ProductReviewForm
from django.contrib import messages

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.core import serializers

import calendar
from django.db.models import Count, Avg
from django.db.models.functions import ExtractMonth

from userauths.models import ContactUs

from userauths.models import Profile

import stripe

from django.conf import settings

def index(requets):
    
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured = True)
    
    context = {
        'products':products
    }
    return render(requets,'core/index.html',context)

def category_list_view(request):
    
    categories = Category.objects.all()
    # .annotate(product_count = Count("product"))
    
    context = {
        "categories" : categories
    }
    return render(request,'core/categories.html', context)

# def category_product_list_view(request, cid):
#     category = Category.object.get(cid = cid)
#     products = Product.objects.filter(product_status="published",category = category)
    
#     context ={
#         "category": category,
#         "products": products,
#     }
#     return render(request, "core/category-product-list.html", context)

def product_list_view(request):
    
    products = Product.objects.filter(product_status= "published")
    
    context = {
        "products":products
    }
    
    return render(request,'core/product-list.html',context)

def product_list_category_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category= category)
    
    context = {
        "category":category,
        "products":products,
    }
    return render(request,"core/category-productlist.html",context)

def vendor_list_view(request):
    vendor = Vendor.objects.all()
    context = {
        "vendor" : vendor,
    }
    return render(request, "core/vendor-list.html",context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid = vid)
    products = Product.objects.filter( vendor= vendor, product_status="published")
    context = {
        "vendor" : vendor,
        "products":products,
    }
    return render(request, "core/vendor-detail-list.html",context)
    
    
    

def product_detail_view(request,pid):
    
    product = Product.objects.get(pid=pid)
    p_image = product.p_images.all()
    products = Product.objects.filter(category = product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product)
    
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    review_form = ProductReviewForm()
    
    make_review = True
    
    if request.user.is_authenticated:
        
        user_review_count = ProductReview.objects.filter(user = request.user, product = product).count()
        
        if user_review_count > 0:
            make_review = False
    
    
    context = {
        "product":product,
        "review_form":review_form,
        "p_image":p_image,
        "products":products,
        "reviews":reviews,
        "average_rating":average_rating,
    }
    
    return render(request,"core/product-detail.html",context)

def tag_list(request, tag_slug = None):
    
    product = Product.objects.filter(product_status = "published").order_by("id")
    
    tag = None
    
    if tag_slug:
        tag = get_list_or_404(Tag, slug = tag_slug)
        products = product.filter(tags__in=[tag])
        
    context ={
        "products" : products
    }
    
    return render(request,"core/tag.html",context)




def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating']
    )
    context = {
        'user' : user.username,
        'review': request.POST['review'],
        'rating':request.POST['rating'],
    }
    
    average_reviews = ProductReview.objects.filter(product = product).aggregate(rating=Avg("rating"))
    
    return JsonResponse(
        {
        'bool': True,
        'context':context,
        'average_reviews':average_reviews 
        }
    )
    
    
def search_view(request):
    
    query = request.GET.get("q")
        
    products = Product.objects.filter(title__icontains=query).order_by("-date")
        
    context = {
            "products":products,
            "query":query,
        }
    return render(request, "core/search.html", context)

def add_to_cart(request):
    
    cart_product = {}
    
    cart_product[str(request.GET['id'])] = {
         'title':request.GET['title'],
         'qty': request.GET['qty'],
         'price': request.GET['price'],
         'image':request.GET['image'],
         'pid':request.GET['pid'],
    }
    
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            
            
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
            
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
            
    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems':len(request.session['cart_data_obj'])})

def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()
    
    min_price   = request.GET['min_price']
    max_price   = request.GET['max_price']
    
    products = products.filter(price__gte = min_price)
    products = products.filter(price__lte = max_price)
    
    
    
    if len(categories) > 0 :
        products = products.filter(category__id__in = categories).distinct()
    if len(vendors) > 0 :
        products = products.filter(vendor__id__in = vendors).distinct()
        
    data = render_to_string("core/asyns/product-list.html",{"products":products})
    
    return JsonResponse({"data":data})


def cart_view(request): 
    cart_total_amount = 0
    
    # return render(request,"core/cart.html")
    
    if 'cart_data_obj' in request.session:
        for p_id,item in request.session['cart_data_obj'].items():
            
            cart_total_amount += int(item['qty']) * float(item['price'])
            
        return render(request, "core/cart.html",
                      {"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    
    else:
        messages.warning(request,"your cart is empty")
        return render(request, "core/cart.html")
    
    
    
def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
         cart_data = request.session['cart_data_obj']
         del request.session['cart_data_obj'][product_id]
         request.session['cart_data_obj']= cart_data
        
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id,item in request.session['cart_data_obj'].items():
            
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = render_to_string("core/asyns/cart-list.html",{"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
            
        
        
    return JsonResponse({"data":context,'totalcartitems':len(request.session['cart_data_obj'])})

def update_from_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
         cart_data = request.session['cart_data_obj']
         cart_data[str(request.GET['id'])]['qty']= product_qty
         request.session['cart_data_obj']= cart_data
        
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id,item in request.session['cart_data_obj'].items():
            
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = render_to_string("core/asyns/cart-list.html",{"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
            
        
        
    return JsonResponse({"data":context,'totalcartitems':len(request.session['cart_data_obj'])})


def save_checkout_info(request):
    cart_total_amount = 0
    total_amount = 0

    if request.method == "POST":
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        address = request.POST.get("address")
        city = request.POST.get("city")
        state = request.POST.get("state")
        country = request.POST.get("country")

templates/core/cart.html
 
 {% extends "patials/base.html" %}
 {% load static %}
 {% block content %}

 <main class="main" id="cart-list">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Cart
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Your Cart</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{totalcartitems}}</span> products in your cart</h6>
                    <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
                </div>
            </div>
        </div>
        <form action="{% url 'core:save-checkout-info' %}" method="POST">
            {% csrf_token %}
        <div class="row">
            <div class="col-lg-8">
                <div class="table-responsive shopping-summery">
                    <table class="table table-wishlist">
                        <thead>
                            <tr class="main-heading">
                                <th scope="col" colspan="2">Product</th>
                                <th scope="col">Title</th>
                                <th scope="col">Unit Price</th>
                                <th scope="col"class="text-center" >Quantity</th>
                                <th scope="col">Subtotal</th>
                                <th scope="col" class="">Refresh</th>
                                <th scope="col" class="end">Remove</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for product_id, item in cart_data.items %}
                            <tr class="pt-30">
                                <td class="custome-checkbox pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                    <label class="form-check-label" for="exampleCheckbox1"></label>
                                </td>
                                <td class="image product-thumbnail pt-40"><img src="{{item.image}}" alt="#"></td>
                                <td class="product-des product-name">
                                    <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-detail' item.pid %}">{{item.title}}</a></h6>
                                   
                                </td>
                                <td class="price" data-title="Price">
                                    <h4 class="text-body">{{item.price|floatformat:2}}</h4>
                                </td>
                                <td class="text-center detail-info" data-title="Stock">
                                    <div class=" mr-15">
                                       <input type="text" class="w-25 product-qty-{{product_id}}" name="" value="{{item.qty}}" id = "product-qty-{{product_id}}">
                                    </div>
                                </td>
                                <td class="price" data-title="Price">
                                    <h4 class="text-brand">
                                        ${% widthratio item.price 1 item.qty %} </h4>
                                </td>
                                {% comment %} <td class="action text-center" data-title="Refresh"><a href="#" class="text-body"><i class="fi-rs-refresh"></i></a></td> {% endcomment %}
                                <td class="action text-center" data-title="Refresh"><button style="border:none; background:none" class="text-body update-product" data-product="{{product_id}}"><i class="fi-rs-refresh"></i></button></td>

                                <td class="action text-center" data-title="Remove"><button style="border:none; background:none" class="text-body delete-product" data-product="{{product_id}}"><i class="fi-rs-trash"></i></button></td>


                            </tr>
                            {% endfor %}
                       
                        </tbody>
                    </table>
                    <div class="row mt-4">
                        <h4 class="mb-30">Bio Data</h4>
                        <div class="row">
                            <div class="form-group col-lg-12">
                                <label class="">Full name</label>
                                <input type="text" required="" name="full_name" value="" placeholder="full name">
                            </div>
                            <div class="form-group col-lg-6">
                                <label class="">Email</label>
                                <input type="text" required="" name="email" value="" placeholder="Email">
                            </div>
                            <div class="form-group col-lg-6">
                                <label class="">Mobile</label>
                                <input type="text" required="" name="mobile" value="" placeholder="Mobile">
                            </div>
                        </div>
                        <h4 class="mb-30">Shipping details</h4>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <label class="">Address</label>
                                <input type="text" required="" name="address" value="" placeholder="Address">
                            </div>
                            <div class="form-group col-lg-6">
                                <label class="">City</label>
                                <input type="text" required="" name="city" value="" placeholder="City">
                            </div>
                            <div class="form-group col-lg-6">
                                <label class="">State</label>
                                <input type="text" required="" name="state" value="" placeholder="State">
                            </div>
                            <div class="form-group col-lg-6">
                                <label class="">Country</label>
                                <input type="text" required="" name="country" value="" placeholder="Country">
                            </div>
                        </div>

                    </div>


                
                </div>
               
                
            </div>
            <div class="col-lg-4">
                <div class="border p-md-4 cart-totals ml-30">
                    <div class="table-responsive">
                        <table class="table no-border">
                            <tbody>
                                <tr>
                                    <td class="cart_total_label">
                                        <h6 class="text-muted">Subtotal</h6>
                                    </td>
                                    <td class="cart_total_amount">
                                        <h4 class="text-brand text-end">${{cart_total_amount|floatformat:2}}</h4>
                                    </td>
                                </tr>
                                <tr>
                                    <td scope="col" colspan="2">
                                        <div class="divider-2 mt-10 mb-10"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="cart_total_label">
                                        <h6 class="text-muted">Shipping</h6>
                                    </td>
                                    <td class="cart_total_amount">
                                        <h5 class="text-heading text-end">Free</h4>
                                    </td> </tr> <tr>

                                  
                                </tr>
                                <tr>
                                    <td class="cart_total_label">
                                        <h6 class="text-muted">Total</h6>
                                    </td>
                                    <td class="cart_total_amount">
                                        <h4 class="text-brand text-end">{{cart_total_amount|floatformat:2}}</h4>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    {% if totalcartitems %}
                    <button href="" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                    {% endif %}
                </div>
            </div>
        </div>
       </form>
    </div>
</main>


 {% endblock content %}

templates/core/category-productlist.html
 
 {% extends "patials/base.html" %}
 {% load static %}
 {% block content %}

    <!-- End Header Section -->

    <!-- Start Slider Section -->
    <main class="main">
        <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">{{category.title}}</h1>
                            <div class="breadcrumb">
                                <a href="index.html" rel="nofollow">
                                    <i class="fi-rs-home mr-5"></i>
                                    Home
                                </a>
                                <span></span> category
                                <span></span> {{category.title}}

                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-30">
            <div class="row">
                
                <div class="col-12">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We found <strong class="text-brand">{{products.count}}</strong> items for you!</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Featured</a></li>
                                        <li><a href="#">Price: Low to High</a></li>
                                        <li><a href="#">Price: High to Low</a></li>
                                        <li><a href="#">Release Date</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row product-grid">
                        {% for p in products %}
                        <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url 'core:product-detail' p.pid %}">
                                            <img class="default-img" src="{{p.image.url}}" alt="" />
                                            <img class="hover-img" src="{{p.image.url}}" alt="" />
                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                                        <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                                        <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                                    </div>
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">{{p.get_precentage|floatformat}}%</span>
                                    </div>
                                </div>
                                <div class="product-content-wrap">
                                    <div class="product-category">
                                        <a href="shop-grid-right.html">{{p.category.title}}</a>
                                    </div>
                                    <h2><a href="{% url 'core:product-detail' p.pid %}">{{p.title}}</a></h2>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div>
                                        <span class="font-small text-muted">By <a href="vendor-details-1.html">{{p.Vendor.title}}</a></span>
                                    </div>
                                    <div class="product-card-bottom">
                                        <div class="product-price">
                                            <span>{{p.price}}</span>
                                            <span class="old-price">{{p.old_price}}</span>
                                        </div>
                                        <div class="add-cart">
                                            <a class="add" href="shop-cart.html"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%endfor %}
                    </div>
                    <!--product grid-->
                  
                    <!--End Deals-->
                </div>
            </div>
        </div>
    </main>
    <!-- End Slider Section -->

    <!-- Start Content Sidebar Section -->

    <!-- End Content Sidebar Section -->

    <!-- End Newsletter Section -->

    <!-- Start Footer Section -->
    {% endblock content %}

templates/core/payment-failed.html
{% extends "patials/base.html" %}
{% load static %}
{% block content %}
<main class="main page-404">
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-10 col-md-12 m-auto text-center">
                    <p class="mb-20"><img src="assets/imgs/page/page-404.png" alt="" class="hover-up" /></p>
                    <h1 class="display-2 mb-30">Payment failed</h1>
                   
                    <a class="btn btn-default submit-auto-width font-xs hover-up mt-30" href="index.html"><i class="fi-rs-home mr-5"></i> Back To Home Page</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}