core/urls.py
from django.urls import path, include
from core.panties import index
from . import views

app_name  = "core"

urlpatterns = [
    path("",views.index,name="index"),
    
    path("products/",views.product_list_view,name="product-list"),
    
    path("category/",views.category_list_view,name="category-list"),
    path("category/<cid>",views.product_list_category_view,name="category-product-list"),
    
    path("vendors/",views.vendor_list_view,name="vendor-list"),
    path("vendors/<vid>",views.vendor_detail_view,name="vendor-detail"),
    
    
    path("products/<pid>/",views.product_detail_view,name="product-detail"),
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),
    
    
    path("ajax-add-review/<int:pid>/",views.ajax_add_review,name="ajax-add-review"),
    
    path("search/",views.search_view, name="search"),
    
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    
    path("cart/", views.cart_view, name="cart"),
    
    path("filter-products/", views.filter_product, name="filter-product"),
    
    path("delete-from-cart/", views.delete_item_from_cart,name="delete-from-cart"),
    path("update-cart/", views.update_from_cart,name="update-cart"),
    
    
    path("checkout/<oid>/", views.checkout,name="checkout"),
    
    path("paypal/", include('paypal.standard.ipn.urls')),
    
    path("payment-completed/<oid>", views.payment_completed_view,name="payment-completed"),
    # path("payment-completed/", views.payment_completed_view,name="payment-completed"),
    
    path("payment-failed/", views.payment_failed_view,name="payment-failed"),
    
    
    path("dashboard/", views.customer_dashboard,name="dashboard"),
    
    path("dashboard/order/<int:id>", views.order_detail,name="order-detail"),
    
    path("make-default-address", views.make_address_default,name="make-default-address"),
    
    path("wishlist/", views.wishlist_view,name="wishlist"),
    path("add-to-wishlist/",views.add_to_wishlist,name="add-to-wishlist"),
    path("remove-from-wishlist/",views.remove_wishlist,name="remove-from-wishlist"),

    
    path("contact/",views.contact,name="contact"),
    path("ajax-contact-form/",views.ajax_contact_form,name="ajax_contact"),
    
    
    
    path("save_checkout_info/",views.save_checkout_info, name="save-checkout-info"),
    
    path("api/create_checkout_session/<oid>/", views.create_checkout_session,name="create_checkout_session")

    
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("useradmin/",include("useradmin.urls")),

]
if settings.DEBUG:
    
 urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("profile/update/", views.profile_update, name="profile-update"),
    
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
  

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True)
    username  = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username
    
class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    subject = models.CharField(max_length=200) 
    message = models.TextField()
    
    class Meta:
        verbose_name = "ContactUs"
        verbose_name_plural = "ContactUs"
        

    def __str__(self):
        return self.full_name

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image")
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"



def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/views.py
from django.shortcuts import render,redirect
from userauths.form import UserRegisterForm, ProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import Profile, User
from django.contrib.auth.decorators import login_required


# User = settings.AUTH_USER_MODEL
# Create your views here.
def register_view(request):
    
    
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user =  form.save()
            username = form.cleaned_data.get("username")
            
            messages.success(request, f"Hey {username}, ban da dang ky thanh cong")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password = form.cleaned_data['password1'])
            login(request,new_user)
            return redirect("core:index")
        print("dang ky thanh cong")
    
    else:
        print("khong the dang ky")
    
    form = UserRegisterForm()
    
    context = {
        'form' : form,
    }
    return render(request, "userauths/sign-up.html",context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request,f"ban da dang nhap")
        return redirect("core:index")
    
    
    
    if request.method == "POST":
        email = request.POST.get("email")
        password =  request.POST.get("password")
        
        # try:
        #     user = User.object.get(email = email)
            
            
        # except:
        #     messages.warning(request,f"User with {email} does not exit")
            
        user  =  authenticate(request, email = email, password = password)
           
        if user is not None:
            login(request,user)
            messages.success(request,"dang nhap thanh cong")
            return redirect("core:index")
        else:
             messages.warning(request,"nguoi dun gko ton tai")
        
    return render(request, "userauths\sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request,"you logged out")
    return redirect("userauths:sign-in")

@login_required
def profile_update(request):
    
    profile = Profile.objects.get( user=request.user )
   
    if request.method == "POST":
        
      form = ProfileForm(request.POST, request.FILES,  instance=profile)
      if form.is_valid():
          new_form = form.save(commit=False)
          new_form.user = request.user
          new_form.save()
          messages.success(request,"update successfully")
          return redirect("core:dashboard")
    else:
     form = ProfileForm( instance=profile)
     
    context = {
        "form": form,
        "profile": profile,
        
    }
    
    return render(request, "userauths/profile-update.html",context)

templates/userauths/profile-update.html
{% extends "patials/base.html" %}
 {% load static %}
 {% block content %}
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow">Home<i class="fi-rs-home mr-5"></i></a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="dashboard-menu">
                                <ul class="nav flex-column" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="#dashboard" role="tab" aria-controls="dashboard" aria-selected="false"><i class="fi-rs-user mr-10"></i>Profile</a>
                                    </li>
                                  
                              
                                    <li class="nav-item">
                                        <a class="nav-link" href="page-login.html"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="tab-content account dashboard-content pl-50">
                                <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="dashboard-tab">
                                    <div class="card">
                                        <div class="card-header border-bottom">
                                            <h3 class="mb-0">Update My Profile</h3>
                                        </div>
                                        {% if form.errors %}
                                        <div class="alert-danger alert">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}
                                        <div class="card-body mb-2" style="display: flex; align-items: center ; gap:10px">


                                            {% if profile.image %}
                                            <span><img src="{{profile.image.url}}" style="width:150px;object-fit:cover;border-radius:50%"></span>
                                            {% else %}
                                            <span><img src="{% static 'assets\imgs\blog\author-1.png' %}" style="width:150px;object-fit:cover;border-radius:50%"></span>
                                            {% endif %}
                                        </div>
                                        <div class="card-body mb-2">
                                            <div>
                                                <form action="" method="POST" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                <div class="mb-3">
                                                    {{form.full_name}}
                                                </div>
                                               <div class="mb-3">
                                                    {{form.image|truncatechars:40}}
                                                </div>
                                               
                                                <div class="mb-3">
                                                    {{form.bio}}
                                                </div>
                                                <div class="mb-3">
                                                    {{form.phone}}
                                                </div>
                                                <button class="btn btn-success" type="submit">Save profile</button>
                                            </form>
                                            </div>
                                        
                                               {% comment %} <button class="btn btn-success" type="submit">Save profile</button> {% endcomment %}
                                          




                                            
                                        </div>
                                    </div>
                                </div>
                         
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


    {% endblock content %}

templates/userauths/sign-in.html
{% extends 'patials/base.html' %}
{% load static %}
{% block content %}
{% comment %}    
<ul class="header_list text-text-md-center text-center">
  <li>
    
    <a href="#test-popup1" class="open-popup-link">Login</a>
      <div id="test-popup2" class="white-popup lr-popup ">
          <h4>Login</h4>
    
          <form class="subscribe-popup-form" method="POST" action="">
              {% csrf_token %}
            <input name="email"  required type="email" placeholder="Enter Your Email">
            <input name="password"  required type="password" placeholder="Enter Your Password">
              <button class="btn btn-primary" title="" type="submit">Login</button>
          </form>
          <h6>Don't have an account?</h6>
          <a href="{% url 'userauths:sign-up' %}" class=""><h6>Click here to Sign up</h6></a>
      </div>
  </li>
</ul> {% endcomment %}
  

<main class="main pages">
  <div class="page-header breadcrumb-wrap">
      <div class="container">
          <div class="breadcrumb">
              <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
              <span></span> Pages <span></span> My Account
          </div>
      </div>
  </div>
  <div class="page-content pt-150 pb-150">
      <div class="container">
          <div class="row">
              <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                  <div class="row">
                      <div class="col-lg-6 pr-30 d-none d-lg-block">
                          <img class="border-radius-15" src="assets/imgs/page/login-1.png" alt="" />
                      </div>
                      <div class="col-lg-6 col-md-8">
                          <div class="login_wrap widget-taber-content background-white">
                              <div class="padding_eight_all bg-white">
                                  <div class="heading_s1">
                                      <h1 class="mb-5">Login</h1>
                                      <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                  </div>
                                  <form method="POST" action="">
                                    {% csrf_token %}
                                      <div class="form-group">
                                          <input type="text" required="" name="email" placeholder="Username or Email *" />
                                      </div>
                                      <div class="form-group">
                                          <input required="" type="password" name="password" placeholder="Your password *" />
                                      </div>
                                
                                      <div class="login_footer form-group mb-50">
                                          <div class="chek-form">
                                              <div class="custome-checkbox">
                                                  <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                  <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                              </div>
                                          </div>
                                          <a class="text-muted" href="#">Forgot password?</a>
                                      </div>
                                      <div class="form-group">
                                          <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                      </div>
                                  </form>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>

{% endblock content %} 

templates/userauths/sign-up.html
{% extends 'patials/base.html' %}
{% load static %}
{% block content %}
   
  
<main class="main pages">
  <div class="page-header breadcrumb-wrap">
      <div class="container">
          <div class="breadcrumb">
              <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
              <span></span> Pages <span></span> My Account
          </div>
      </div>
  </div>
  <div class="page-content pt-150 pb-150">
      <div class="container">
          <div class="row">
              <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                  <div class="row">
                      <div class="col-lg-6 col-md-8">
                          <div class="login_wrap widget-taber-content background-white">
                              <div class="padding_eight_all bg-white">
                                  <div class="heading_s1">
                                      <h1 class="mb-5">Create an Account</h1>
                                      <p class="mb-30">Already have an account? <a href="{% url 'userauths:sign-in' %}">Login</a></p>
                                  </div>
                                  {% if form.errors %}
          <div class="alert alert-danger">
            <strong>{{form.errors}}</strong>
          </div>
          {% endif %}
                                  <form method="POST" action="">
                                    {% csrf_token %}
                                    <div class="form-group">
                                    {{form.username}}
                                    </div>
                                    <div class="form-group">
                                    {{form.email}}
                                  </div>

                                    <div class="form-group">
                                    {{form.password1}}
                                  </div>

                                    <div class="form-group">
                                    {{form.password2}}
                                  </div>
                                    
                                      <div class="login_footer form-group mb-50">
                                          <div class="chek-form">
                                              <div class="custome-checkbox">
                                                  <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox12" value="" />
                                                  <label class="form-check-label" for="exampleCheckbox12"><span>I agree to terms &amp; Policy.</span></label>
                                              </div>
                                          </div>
                                          <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Lean more</a>
                                      </div>
                                      <div class="form-group mb-30">
                                          <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">Submit &amp; Register</button>
                                      </div>
                                      <p class="font-xs text-muted"><strong>Note:</strong>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy</p>
                                  </form>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-6 pr-30 d-none d-lg-block">
                          <div class="card-login mt-115">
                              <a href="#" class="social-login facebook-login">
                                  <img src="{% static 'assets/imgs/theme/icons/logo-facebook.svg' %}" alt="" />
                                  <span>Continue with Facebook</span>
                              </a>
                              <a href="#" class="social-login google-login">
                                  <img src="{% static 'assets/imgs/theme/icons/logo-google.svg' %}" alt="" />
                                  <span>Continue with Google</span>
                              </a>
                              <a href="#" class="social-login apple-login">
                                  <img src="{% static 'assets/imgs/theme/icons/logo-apple.svg' %}" alt="" />
                                  <span>Continue with Apple</span>
                              </a>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>

{% endblock content %} 